### ISSUE TITLE
Can't run scenes

### ISSUE THREAD

**Issue by SimonDarksideJ** [Innoactive/IA-unity-VR-toolkit-VRTK#11]
When trying to run the project, all I get is the following error:
"Graphics.CopyTexture called with region not fitting in destination element (dstX 0, dstY 0, srcWidth 1792, srcHeight 1767, dstMip 0)"

Not sure why as I compared your camera code to my own and it's pretty similar, is this a VRTK issue

**Comment by tomwim** [comment]
I cannot reproduce this error...

**Comment by SimonDarksideJ** [comment]
Hmm, ok will re-test using your latest commits.

Just be sure to "clean" your repo (once all new files are added :D) so the Library and temp folders are obliterated. (make sure Unity is closed first!)

**Comment by SimonDarksideJ** [comment]
Ok, issue has gone, closing
