### ISSUE TITLE
Reorder usings

### ISSUE THREAD

**Issue by SimonDarksideJ** [Innoactive/IA-unity-VR-toolkit-VRTK#12]
Noted the usings in each file are not right.

Unity classes should be outside the #if defines (UnityEngine, System.Collections, UnityEngine.XR, etc
Unity.xr.wsa should be INSIDE the #if defines (Unity.XR.WSA, Unity.XR.WSA.Input, etc)

**Comment by tomwim** [comment]
All usings are now properly set within the defines

**Comment by SimonDarksideJ** [comment]
Some usings are still leaking :D 

> Assets/VRTK/Source/SDK/WindowsMR/Additional/WindowsMR_TrackedObject.cs(72,17): error CS0246: The type or namespace name `InteractionSourceHandedness' could not be found. Are you missing `UnityEngine.XR.WSA.Input' using directive?

**Comment by tomwim** [comment]
Sorry about that. Fixed and pushed. 
Closed

**Comment by SimonDarksideJ** [comment]
:D 
I find it best to test by "Switching" platforms and checking Unity doesn't throw anything at you.  Horrible when some assets do that :P
