### ISSUE TITLE
Check VRTK Manager config and add Windows MR to all scenes

### ISSUE THREAD

**Issue by SimonDarksideJ** [Innoactive/IA-unity-VR-toolkit-VRTK#13]
One thing I had to do, was walk through all the scenes and ensure that both:

- WindowsMR was added to the SDK_Setups (which does seem to be the case.
- Windows MR was added to the SDK_Manager component, which does not seem to be configured in all cases

**Comment by tomwim** [comment]
I added WindowsMR to the SDK Setup and is configured in every example scene

**Comment by SimonDarksideJ** [comment]
Confirmed, all scenes now setup correctly
