### ISSUE TITLE
Shouldn't use "Update" Loop to check Controller activity.

### ISSUE THREAD

**Issue by SimonDarksideJ** [Innoactive/IA-unity-VR-toolkit-VRTK#14]
Controllers with Windows MR use events rather than the update loop to check controller states.

See the attached class which is the implementation I'm working on for the Unity Editor VR project.

In short, you update the "InteractionManager" each update and then handle the events has it happens.

```
            InteractionManager.GetCurrentReading(m_States);

            InteractionManager.InteractionSourceUpdated += OnUpdated;
            InteractionManager.InteractionSourcePressed += OnSourcePressed;
            InteractionManager.InteractionSourceReleased += OnSourceReleased;

```

[WindowsMRInputToEvents.cs.log](https://github.com/Innoactive/IA-unity-VR-toolkit-VRTK/files/1441711/WindowsMRInputToEvents.cs.log)

> renamed cs file to .log for github

**Comment by tomwim** [comment]
In my first version I used the events to handle controller input but it did not work as expected. That's why I decided to update the controller state in Update.

The issue I face right now is that when I press the select button, in OnSourcePressed state.selectPressed is False in more than 75% of the cases. This just causes problems that were avoided by Update. Do you have any idea why this happens (only with Select)?

**Comment by tomwim** [comment]
Just figured out selectPressed is only True if selectPressedAmount is 1. So the event is called when the amount changes, but if you press the button fast (like you would normally do) the selectPressAmount does not always reach 1...So I think a workaround is needed in the Select case?

**Comment by SimonDarksideJ** [comment]
For the trigger (like with the other SDK's), pressed is if the selectPressedAmount  > 0 but you should also have somewhere that provides the float value for triggers.  Best ask @thestonefox where that might be.

Pressed effectively means "hold" for triggers.

**Comment by tomwim** [comment]
Apparently Microsoft handles Pressed differently and says Pressed is if selectedPressedAmount == 1.
But no matter if it's >0 or =1, we fall in the same problem which is the reason why I used Update in the first place. 

InteractionSourceUpdated is not synchronized with Unitys Update function but VRTK polls the button state from the Update Loop. So the previous state of a button can already be overwritten before VRTK knows about it and therefore GetPressDown and GetPressUp are lost. Listening to selectedPressedAmount causes the same issue though.

**Comment by thestonefox** [comment]
One of the things i've been thinking about (probably for v4 VRTK) is ditching the whole `VRTK_ControllerEvents.cs` script and instead (along with an SDK cleanup!) having the SDK scripts responsible for doing sensible things.

So SteamVR and Oculus SDK SDK scripts would simply handle their own Update loop and emit events for when the controller is interacted with (a generic event as well, not an event per button type)

This would mean that more sensible SDKs that use events for button interactions (like the windows MR one) would simply just need to bubble the event through the VRTK sdk bridge and wouldn't need a loop as there is now.

**Comment by SimonDarksideJ** [comment]
I would +10 that move.
I've been working with the EditorVR team to get WindowsMR support in there and that is the same model they use.  Granted they are using the experimental input system but I think it would work with the traditional one as well.

**Comment by thestonefox** [comment]
I wish that experimental input system would be released already!

We're planning on adding our own input abstraction to vrtk because the new one has been delayed again :(

**Comment by SimonDarksideJ** [comment]
Sheesh, tell me about it.  It's like the new 2D system, bits and drabs here and there but never delivering on it's original promises :S

**Comment by tomwim** [comment]
So the idea is to stay with a workaround for now (for the select button)? I actually have no idea how to handle it properly otherwise...

**Comment by thestonefox** [comment]
@tomwim Yeah I guess workaround now, stick with the old VRTK style, with a plan to move away from that and to make the SDK integration more decoupled and cleaner in a future version of VRTK (probably v4)
