### ISSUE TITLE
Exception: 'VRTK.SDK_WindowsMRBoundaries' is not a subclass of the SDK base type 

### ISSUE THREAD

**Issue by SimonDarksideJ** [Innoactive/IA-unity-VR-toolkit-VRTK#16]
Exception: 'VRTK.SDK_WindowsMRBoundaries' is not a subclass of the SDK base type 'SDK_BaseBoundaries'.
Parameter name: actualTypeName
VRTK.SDK_WindowsMRBoundaries
VRTK.VRTK_Logger.Log (LogLevels level, System.String message) (at Assets/VRTK/Source/Scripts/Internal/VRTK_Logger.cs:167)
VRTK.VRTK_Logger.Fatal (System.Exception exception) (at Assets/VRTK/Source/Scripts/Internal/VRTK_Logger.cs:138)
VRTK.VRTK_SDKInfo.SetUp (System.Type baseType, System.Type fallbackType, System.String actualTypeName, Int32 descriptionIndex) (at Assets/VRTK/Source/Scripts/Utilities/SDK/VRTK_SDKInfo.cs:138)
VRTK.VRTK_SDKInfo.OnAfterDeserialize () (at Assets/VRTK/Source/Scripts/Utilities/SDK/VRTK_SDKInfo.cs:163)

Not sure as to the source of this error, shows up in the MRTP 4 build on the current commit

**Comment by tomwim** [comment]
Found the same problem and fixed it. Fallback was set incorrectly
