### ISSUE TITLE
Controller Model not visualized

### ISSUE THREAD

**Issue by tomwim** [Innoactive/IA-unity-VR-toolkit-VRTK#17]
The Controller Models are not visualized yet. They have to be loaded with GLTF at runtime.

This currently only works as Windows 10 API call and therefore will not work within the Unity Editor. So besides visualizing the controllers a proper placeholder object has to be found.

**Comment by SimonDarksideJ** [comment]
If you check the MRTK, they have gLTF importers and have the models rendering in the editor and platform.

**Comment by tomwim** [comment]
So rendering in the Editor works now, too? That would be amazing! I tried the MRTK stuff before which did not work as I wanted, but I'll give it another try.

**Comment by hellobardgames** [comment]
Would love to see this working, this is pretty much the only thing stopping me from making a release. Thank you so much for all the work you've done!

**Comment by tomwim** [comment]
Controller models should be implemented by the end of the week

**Comment by tomwim** [comment]
Sorry for the delay. I added the controllers and they are visualized within Unity but I get unexpected Build errors which I don't know where they come from yet. Maybe it works for you though.

**Comment by hellobardgames** [comment]
Great, thanks! I'll give it a go this weekend

**Comment by tomwim** [comment]
The controllers are visualized now and work in editor and build
