### ISSUE TITLE
Haptic Pulse

### ISSUE THREAD

**Issue by tomwim** [Innoactive/IA-unity-VR-toolkit-VRTK#18]
The Haptic Pulse is not implemented yet.
This currently only works as Windows 10 API call and therefore will not work within the Unity Editor.

**Comment by SimonDarksideJ** [comment]
I didn't think the handsets had haptic feedback.  Where did you see this in the API?  But doesn't surprise me the editor doesn't have support for it, the other SDK's have to provide that natively.
But easy enough to access with a small interop bridge.

**Comment by tomwim** [comment]
I thought the MRTK Controller example had haptic feedback on grasp. And some guy on Slack said he got haptic feedback working (only built) but I couldnt get in touch with him yet.
