### ISSUE TITLE
Example #37 Climbing and Falling - No Falling and Height offset

### ISSUE THREAD

**Issue by tomwim** [Innoactive/IA-unity-VR-toolkit-VRTK#20]
In Example 37 after climbing up the user does not fall down as intended. Additionally, after the user climbed up the height offset is kept after teleporting.

Issue might be a incorrect set Rigidbody.

**Comment by SimonDarksideJ** [comment]
Lol, I thought that was just the example, as the "body" isn't provided by the SDK.  Is falling supported in the other SDK's?

**Comment by tomwim** [comment]
Yes, with Oculus the falling works. I was hoping it's intended as well ;)
