### ISSUE TITLE
Move Controller Updates to Update Loop instead of Update Event

### ISSUE THREAD

**Issue by tomwim** [Innoactive/IA-unity-VR-toolkit-VRTK#22]
Update controller states in Update Loop instead of events.

Causes issues with GetPressUp and GetPressDown since the previous state is never overridden again and stays as if button was just Pressed or just Released. This is caused by VRTKs polling of the current states.

Should be changed in the future (https://github.com/thestonefox/VRTK/issues/1594).

@DDReaper I currently cannot think about a better way to handle this. That's also something I haven't thought about before changing to events.

**Comment by tomwim** [comment]
Another approach is to simply wait one frame after an Update through Release or Pressed and then set the previous state to the current state.

**Comment by SimonDarksideJ** [comment]
Will try and set some time to check on your latest commits.
