### ISSUE TITLE
Loading a level causes crash in editor

### ISSUE THREAD

**Issue by hellobardgames** [Innoactive/IA-unity-VR-toolkit-VRTK#24]
This may be specific to my project, but loading scenes with the sceneManager causes a Unity crash in the editor. When running a build made with Visual Studio, the screen goes to black. 

I've tried my normal scene loading script that does a little extra (based off SteamVR's script), but even a simple "SceneManager.LoadScene(levelToLoad, LoadSceneMode.Single);" sends it straight to a crash.

The same levels load if I just open them directly as scenes. Is this an issue with anyone else? My Unity version is Unity 2017.2.0p1-MRTP4 (64-bit) and using the latest version of your repo.

**Comment by tomwim** [comment]
I have the same issue. Will look into it as soon as possible.

**Comment by hellobardgames** [comment]
Good to hear! It's hard to debug, as the Editor log doesnt give me much info about what's causing the crash.

**Comment by tomwim** [comment]
I found the issue and fixed it which also led me to another problem. I will change some stuff so it everything works and then commit it tomorrow (probably).

**Comment by tomwim** [comment]
I fixed the issue and pushed it. The only problem that results is that by changing the scene the controllers get missing and the InteractionSourceDetected event is not triggered anymore cause obviously the source is already detected. Working around that and just load the controller in Update then results in TryGetRenderableModel to fail and not showing the Controller again. Need to find a way around that now...

**Comment by tomwim** [comment]
Actually I am not right.
The TryGetMotionControllerModel function from MRTKs DLL does not work, which is Editor only.
I haven't tested it yet in Build so maybe that works then. Still need a workaround for Editor though.

**Comment by tomwim** [comment]
As I said, fixed the issue and with MRTP-5 the scene change Controller visualization problem is solved as well.
