### ISSUE TITLE
Adding Windows Mixed Reality Headset model names to VRTK

### ISSUE THREAD

**Issue by tomwim** [Innoactive/IA-unity-VR-toolkit-VRTK#25]
All Windows Mixed Reality Headsets of all manufacturers have a specific model name in Unity. For the Acer Headset it's 'acerah100'.

This must be added to SDK_BaseHeadset.Headsets and to VRTK_DeviceFinder's GetHeadsetType function.

Currently only the Acer headset is included.

**Comment by SimonDarksideJ** [comment]
Actually, there is little or no point to adding specific headsets for WMR.  Simply because it's the API's that drive MR, not the headsets.

Instead, it should just add "Mixed Reality" (doubt we could get HL to work).

**Comment by tomwim** [comment]
Not needed
