### ISSUE TITLE
Using MRTP4 - Unity crashes on run from editor

### ISSUE THREAD

**Issue by SimonDarksideJ** [Innoactive/IA-unity-VR-toolkit-VRTK#27]
Something seems broken in the latest round of commits, scene 37 (climbing) crashes Unity when run.

Attaching Crash log for reference. (not looked in to it fully yet.)
[Editor.log](https://github.com/Innoactive/IA-unity-VR-toolkit-VRTK/files/1487299/Editor.log)

**Comment by SimonDarksideJ** [comment]
OK, after a LOT of digging, the crash is caused because the Windows_MR_Controller_Visualizer component hasn't been added to the Controllers in other scenes.
SO I guess the prefab hasn't been synchronised with the changes in the Grab scene.

Also, if I do assign an "alternate" model, it ALSO shows up on top of the controller :P

**Comment by tomwim** [comment]
I fixed that and added the controllers to the project and every scene so it works in editor and build now.

I'll give the alternate model thing a look as soon as possible.

**Comment by SimonDarksideJ** [comment]
Right, will sync and give it another test
