### ISSUE TITLE
Project needs refreshing with the latest VRTK alpha build

### ISSUE THREAD

**Issue by SimonDarksideJ** [Innoactive/IA-unity-VR-toolkit-VRTK#28]
The latest Alpha build just added SteamVR support together with some base SDK notions for Windows MR controllers (mostly names and such)
Need to ensure this repo doesn't fall behind and have issues merging.

You ok with that @tomwim ?

**Comment by tomwim** [comment]
Yeah, I followed the discussion on Slack a little and know what should be coming (more or less). Thanks!
