### ISSUE TITLE
Update Fork to be up-to-date with VRTK's master

### ISSUE THREAD

**Issue by burnedikt** [Innoactive/IA-unity-VR-toolkit-VRTK#6]
## Current State

This fork of [thestonefox/VRTK](https://github.com/thestonefox/VRTK) was initially intended to be used more simply as a submodule. Thus, the `ProjectSettings` and `Assets` folder contained in the original repository were removed and the `VRTK` folder was moved up to the root level. 

However, keeping this fork up to date with VRTK's [master](https://github.com/thestonefox/VRTK) while maintaining our individual changes became very cumbersome...

## Desired State

I created a new master branch ([master-vrtk](https://github.com/Innoactive/IA-unity-VR-toolkit-VRTK/tree/master-vrtk)) which is all set to replace the current master branch. This new master branch essentially contains all the most recent changes from VRTK and our changes (e.g. LeapMotion) have been added on top as new commits. The new `master-vrtk` branch has been tested together with the [holocloud's unity sample app](https://github.com/Innoactive/HOLOCLOUD-unity-sample-app) and apart from requiring minor changes to the [Innoactive VR Toolkit](https://github.com/Innoactive/IA-unity-VR-toolkit/pull/14) as well as the [Holocloud SDK](https://github.com/Innoactive/HOLOCLOUD-unity-sdk/pull/13), everything works fine.

In the future, this branch will be easier to maintain, since we can simply merge in updates from the VRTK upstream or rebase our changes upon theirs. 

Including this repository as a submodule (e.g. in IA-unity-VR-toolkit) still works, though we'll have the `ProjectSettings` in there from now on. However, having these ugly ProjectSettings in there is still a lot less messy than keeping the diverged fork up to date with VRTK's base repository.

The current (and soon to be oudated) master will still be kept around as `master-archived` in case any old project refers to one of the current commits.

JIRA: https://innoactive.instajira.com/browse/HOLOCLOUD-65

**Comment by burnedikt** [comment]
@RobertSchmitzInnoactive, @cutamar, @LukasReindlGit Can you comment on the above? Any objections?

I think we should proceed with this ASAP since we'll keep diverging from VRTK's master otherwise.

**Comment by LukasReindlGit** [comment]
@burnedikt  sehe ich das richtig, dass wir jetzt auf 5.6 switchen sollen?

**Comment by burnedikt** [comment]
@LukasReindlGit Ja, das auch. Aber v.a. gings um das VRTK Update (unabhängig von 5.6). 5.6 wird schon für den Saturn VR Store benutzt und klappert ganz gut.

**Comment by burnedikt** [comment]
@LukasReindlGit @RobertSchmitzInnoactive @cutamar sofern bis heute Abend (03.05.2017 - 18:00 Uhr) keine Einwände mehr kommen, wird der derzeitige `master-vrtk` ab morgen zum neuen `master` und default branch und der derzeitige `master` verbleibt als `master-archived`

**Comment by burnedikt** [comment]
done as of 05/04/2017
